
platform :ios, '13.0'

target 'SampleApp' do
    pod 'OktaLogger/Core', :git => 'https://github.com/okta/okta-logger-swift.git', :tag => '1.3.4'
    pod 'OktaDeviceSDK/Core', :git => 'https://github.com/okta-tardis/okta-devices-swift'
end
