# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  SampleApp:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Install pods
          command: cd Examples/PushSampleApp; pod install
      - run:
          name: "iOS Push Sample App"
          command: xcodebuild -workspace ./Examples/PushSampleApp/SampleApp.xcworkspace -scheme "SampleApp" -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" clean build