version: 2.1

# orbs:
#   general-helpers: atko-devices/eng-services-platform-helpers-general@2.0
#   win-helpers: atko-devices/eng-rps-platform-windows@1.0

############### WORKFLOWS ###############
workflows:
  test-build:
    jobs:
      - build-linux

############### JOBS ###############
jobs:
  build-linux:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: dbus
          command: qdbus --system
  
############### COMMANDS ###############
