# This is a basic workflow that is manually triggered

name: Publish cocoapods release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      email:
        # Email which you used for registration in cocoapods trunk
        description: 'Cocoapods account email'
        # Input has to be provided for the workflow to run
        required: true
      tag:
        # New tag for the release
        description: 'Tag for the release'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  post_release:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Create tag
      run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
    - name: Create session
      run: pod trunk register ${{ github.event.inputs.email }}
    - name: Pod lint
      run: pod lib lint
    - name: Pod publish
      run: pod trunk push DeviceAuthenticator.podspec
